name:                haskell-jvm
version:             0.1.0.0
github:              "limengyu1990/haskell-jvm"
license:             BSD3
author:              "limengyu"
maintainer:          "limengyu199@163.com"
copyright:           "2019 limengyu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/limengyu1990/haskell-jvm#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative == 0.14.3.0
- directory == 1.3.3.2
- filepath == 1.4.1.2
- bytestring == 0.10.8.2
- text == 1.2.3.0
- zip == 1.0.0
- containers == 0.5.10.2
- transformers == 0.5.5.0


library:
  source-dirs: src

executables:
  haskell-jvm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-jvm

tests:
  haskell-jvm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-jvm
